//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.opengi.co.uk", ConfigurationName="OpenGI.OpenInterchange")]
    public interface OpenInterchange
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.opengi.co.uk/OpenInterchange/processMessageRequest", ReplyAction="www.opengi.co.uk/OpenInterchange/processMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OpenGI.processMessageResponse> processMessageAsync(OpenGI.processMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.opengi.co.uk/OpenInterchange/getMessagesRequest", ReplyAction="www.opengi.co.uk/OpenInterchange/getMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OpenGI.getMessagesResponse> getMessagesAsync(OpenGI.getMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.opengi.co.uk/OpenInterchange/returnResponseRequest", ReplyAction="www.opengi.co.uk/OpenInterchange/returnResponseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OpenGI.returnResponseResponse> returnResponseAsync(OpenGI.returnResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.opengi.co.uk/OpenInterchange/xStreamMessageRequest", ReplyAction="www.opengi.co.uk/OpenInterchange/xStreamMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OpenGI.xStreamMessageResponse> xStreamMessageAsync(OpenGI.xStreamMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.opengi.co.uk/OpenInterchange/inStreamMessageRequest", ReplyAction="www.opengi.co.uk/OpenInterchange/inStreamMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OpenGI.inStreamMessageResponse> inStreamMessageAsync(OpenGI.inStreamMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processMessage", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class processMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string branch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marsReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string licenceKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmlSubmission;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeout;
        
        public processMessageRequest()
        {
        }
        
        public processMessageRequest(string messageType, string branch, string marsReference, string bNumber, string licenceKey, string xmlSubmission, int timeout)
        {
            this.messageType = messageType;
            this.branch = branch;
            this.marsReference = marsReference;
            this.bNumber = bNumber;
            this.licenceKey = licenceKey;
            this.xmlSubmission = xmlSubmission;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processMessageResponse", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class processMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public processMessageResponse()
        {
        }
        
        public processMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.opengi.co.uk")]
    public partial class request
    {
        
        private string branchField;
        
        private long idField;
        
        private string licenceKeyField;
        
        private string marsReferenceField;
        
        private string messageTypeField;
        
        private string responseField;
        
        private int timeoutField;
        
        private string xmlSubmissionField;
        
        private string bNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string branch
        {
            get
            {
                return this.branchField;
            }
            set
            {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string licenceKey
        {
            get
            {
                return this.licenceKeyField;
            }
            set
            {
                this.licenceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string marsReference
        {
            get
            {
                return this.marsReferenceField;
            }
            set
            {
                this.marsReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int timeout
        {
            get
            {
                return this.timeoutField;
            }
            set
            {
                this.timeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string xmlSubmission
        {
            get
            {
                return this.xmlSubmissionField;
            }
            set
            {
                this.xmlSubmissionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string bNumber
        {
            get
            {
                return this.bNumberField;
            }
            set
            {
                this.bNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessages", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class getMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marsReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("licenceDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] licenceDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeout;
        
        public getMessagesRequest()
        {
        }
        
        public getMessagesRequest(string marsReference, string bNumber, string[] licenceDetails, int timeout)
        {
            this.marsReference = marsReference;
            this.bNumber = bNumber;
            this.licenceDetails = licenceDetails;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesResponse", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class getMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenGI.request[] @return;
        
        public getMessagesResponse()
        {
        }
        
        public getMessagesResponse(OpenGI.request[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnResponse", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class returnResponseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenGI.request response;
        
        public returnResponseRequest()
        {
        }
        
        public returnResponseRequest(OpenGI.request response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnResponseResponse", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class returnResponseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public returnResponseResponse()
        {
        }
        
        public returnResponseResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="xStreamMessage", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class xStreamMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marsReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string licenceKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmlSubmission;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeout;
        
        public xStreamMessageRequest()
        {
        }
        
        public xStreamMessageRequest(string marsReference, string bNumber, string licenceKey, string xmlSubmission, int timeout)
        {
            this.marsReference = marsReference;
            this.bNumber = bNumber;
            this.licenceKey = licenceKey;
            this.xmlSubmission = xmlSubmission;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="xStreamMessageResponse", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class xStreamMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public xStreamMessageResponse()
        {
        }
        
        public xStreamMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inStreamMessage", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class inStreamMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string branch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marsReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string licenceKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmlSubmission;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeout;
        
        public inStreamMessageRequest()
        {
        }
        
        public inStreamMessageRequest(string branch, string marsReference, string bNumber, string licenceKey, string xmlSubmission, int timeout)
        {
            this.branch = branch;
            this.marsReference = marsReference;
            this.bNumber = bNumber;
            this.licenceKey = licenceKey;
            this.xmlSubmission = xmlSubmission;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inStreamMessageResponse", WrapperNamespace="www.opengi.co.uk", IsWrapped=true)]
    public partial class inStreamMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.opengi.co.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public inStreamMessageResponse()
        {
        }
        
        public inStreamMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface OpenInterchangeChannel : OpenGI.OpenInterchange, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OpenInterchangeClient : System.ServiceModel.ClientBase<OpenGI.OpenInterchange>, OpenGI.OpenInterchange
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OpenInterchangeClient() : 
                base(OpenInterchangeClient.GetDefaultBinding(), OpenInterchangeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OpenInterchangePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenInterchangeClient(EndpointConfiguration endpointConfiguration) : 
                base(OpenInterchangeClient.GetBindingForEndpoint(endpointConfiguration), OpenInterchangeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenInterchangeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OpenInterchangeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenInterchangeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OpenInterchangeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenInterchangeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenGI.processMessageResponse> OpenGI.OpenInterchange.processMessageAsync(OpenGI.processMessageRequest request)
        {
            return base.Channel.processMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenGI.processMessageResponse> processMessageAsync(string messageType, string branch, string marsReference, string bNumber, string licenceKey, string xmlSubmission, int timeout)
        {
            OpenGI.processMessageRequest inValue = new OpenGI.processMessageRequest();
            inValue.messageType = messageType;
            inValue.branch = branch;
            inValue.marsReference = marsReference;
            inValue.bNumber = bNumber;
            inValue.licenceKey = licenceKey;
            inValue.xmlSubmission = xmlSubmission;
            inValue.timeout = timeout;
            return ((OpenGI.OpenInterchange)(this)).processMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenGI.getMessagesResponse> OpenGI.OpenInterchange.getMessagesAsync(OpenGI.getMessagesRequest request)
        {
            return base.Channel.getMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenGI.getMessagesResponse> getMessagesAsync(string marsReference, string bNumber, string[] licenceDetails, int timeout)
        {
            OpenGI.getMessagesRequest inValue = new OpenGI.getMessagesRequest();
            inValue.marsReference = marsReference;
            inValue.bNumber = bNumber;
            inValue.licenceDetails = licenceDetails;
            inValue.timeout = timeout;
            return ((OpenGI.OpenInterchange)(this)).getMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenGI.returnResponseResponse> OpenGI.OpenInterchange.returnResponseAsync(OpenGI.returnResponseRequest request)
        {
            return base.Channel.returnResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenGI.returnResponseResponse> returnResponseAsync(OpenGI.request response)
        {
            OpenGI.returnResponseRequest inValue = new OpenGI.returnResponseRequest();
            inValue.response = response;
            return ((OpenGI.OpenInterchange)(this)).returnResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenGI.xStreamMessageResponse> OpenGI.OpenInterchange.xStreamMessageAsync(OpenGI.xStreamMessageRequest request)
        {
            return base.Channel.xStreamMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenGI.xStreamMessageResponse> xStreamMessageAsync(string marsReference, string bNumber, string licenceKey, string xmlSubmission, int timeout)
        {
            OpenGI.xStreamMessageRequest inValue = new OpenGI.xStreamMessageRequest();
            inValue.marsReference = marsReference;
            inValue.bNumber = bNumber;
            inValue.licenceKey = licenceKey;
            inValue.xmlSubmission = xmlSubmission;
            inValue.timeout = timeout;
            return ((OpenGI.OpenInterchange)(this)).xStreamMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenGI.inStreamMessageResponse> OpenGI.OpenInterchange.inStreamMessageAsync(OpenGI.inStreamMessageRequest request)
        {
            return base.Channel.inStreamMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenGI.inStreamMessageResponse> inStreamMessageAsync(string branch, string marsReference, string bNumber, string licenceKey, string xmlSubmission, int timeout)
        {
            OpenGI.inStreamMessageRequest inValue = new OpenGI.inStreamMessageRequest();
            inValue.branch = branch;
            inValue.marsReference = marsReference;
            inValue.bNumber = bNumber;
            inValue.licenceKey = licenceKey;
            inValue.xmlSubmission = xmlSubmission;
            inValue.timeout = timeout;
            return ((OpenGI.OpenInterchange)(this)).inStreamMessageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OpenInterchangePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OpenInterchangePort))
            {
                return new System.ServiceModel.EndpointAddress("https://openinterchange.openecommerce.co.uk/OpenInterchange/OpenInterchange");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OpenInterchangeClient.GetBindingForEndpoint(EndpointConfiguration.OpenInterchangePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OpenInterchangeClient.GetEndpointAddress(EndpointConfiguration.OpenInterchangePort);
        }
        
        public enum EndpointConfiguration
        {
            
            OpenInterchangePort,
        }
    }
}
